development:
  adapter: postgresql
  encoding: utf8
  database: money_back_development
  pool: 80
  username: postgres
  password: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: money_back_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING
  host: localhost
  template: template0

production: &production
  url:  <%= ENV["RDS_DATABASE_URL"] || ENV["DATABASE_URL"] %>
  pool: <%= ENV["RDS_DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

staging:
  <<: *production
